language: scala
scala:
  - 2.12.4
  - 2.11.11
  - 2.10.6
jdk:
  - oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success: sbt ++$TRAVIS_SCALA_VERSION coveralls
